import { api } from './api.js';

const views=['dashboard','personas','proyectos','capacidades','necesidades','matches','equipos','documentos','pendientes','configuracion'];
const labels={dashboard:'Dashboard',personas:'Personas',proyectos:'Proyectos',capacidades:'Capacidades',necesidades:'Necesidades',matches:'Matches',equipos:'Equipos',documentos:'Documentos',pendientes:'Pendientes',configuracion:'Configuración'};
const columns={
 personas:['id','nombre_completo','profesion','especialidad','estado','fecha_actualizacion'], proyectos:['id','nombre','sector','etapa','estado','fecha_actualizacion'], capacidades:['id','entidad_tipo','entidad_id','capacidad','categoria','estado'], necesidades:['id','entidad_tipo','entidad_id','necesidad','categoria','prioridad','estado'], matches:['id','persona_id','proyecto_id','explicacion','puntuacion','estado'], equipos:['id','nombre','proyecto_id','integrantes','estado'], documentos:['id','nombre','tipo','persona_id','proyecto_id','url','estado_analisis'], pendientes:['id','entidad_tipo','entidad_id','pendiente','prioridad','estado']};
const formFields={
 personas:['nombre_completo','email','telefono','ciudad','departamento','pais','profesion','especialidad','experiencia','seniority','sectores','tecnologias','disponibilidad','intereses','puede_aportar','busca','tiene_proyecto_propio','linkedin','web','observaciones','preguntas_pendientes','estado','origen_informacion'],
 proyectos:['nombre','creador_id','responsables','descripcion','sector','problema','solucion','etapa','tecnologias','evidencia_existente','perfiles_buscados','necesidades_tecnicas','necesidades_comerciales','necesidades_financieras','necesidades_legales','necesidades_hardware','validaciones','piloto','clientes','estado','proximos_pasos','origen_informacion'],
 capacidades:['entidad_tipo','entidad_id','capacidad','categoria','nivel','evidencia','estado','origen_informacion'],
 necesidades:['entidad_tipo','entidad_id','necesidad','categoria','prioridad','detalle','estado','origen_informacion'],
 matches:['estado'], equipos:['nombre','proyecto_id','integrantes','roles','capacidades_cubiertas','capacidades_faltantes','estado','notas','responsable_id','proximos_pasos','origen_informacion'],
 pendientes:['entidad_tipo','entidad_id','pendiente','prioridad','estado','fecha_objetivo','responsable_id','notas','origen_informacion']
};
let current='dashboard';
const app=document.querySelector('#app'), title=document.querySelector('#title'), subtitle=document.querySelector('#subtitle');
const nav=document.querySelector('#nav');
for(const v of views){ const b=document.createElement('button'); b.textContent=labels[v]; b.dataset.view=v; b.onclick=()=>go(v); nav.appendChild(b); }

document.querySelector('#authBtn').onclick=()=>{ const v=prompt('Token de administración de MESA (se guarda solo durante esta sesión):',''); if(v) api.setToken(v); };
document.querySelector('#searchBtn').onclick=searchGlobal; document.querySelector('#globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter')searchGlobal();});

async function go(v){ current=v; location.hash=v; [...nav.children].forEach(b=>b.classList.toggle('active',b.dataset.view===v)); title.textContent=labels[v]; subtitle.textContent=v==='dashboard'?'¿Quién puede ayudar a quién?':'Google Sheets es la fuente de verdad'; app.innerHTML='<div class="content"><div class="empty">Cargando…</div></div>'; try{ if(v==='dashboard') await dashboard(); else if(v==='configuracion') await settings(); else await entityView(v); }catch(e){ fail(e); } }
function esc(v){ return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])); }
function fail(e){ app.innerHTML=`<div class="content"><div class="notice error"><strong>Error:</strong> ${esc(e.message)}</div></div>`; }

async function dashboard(){ const ents=['personas','proyectos','capacidades','necesidades','matches','equipos','pendientes','documentos']; const data=Object.fromEntries(await Promise.all(ents.map(async e=>[e,await api.list(e)]))); const high=(data.matches||[]).filter(x=>Number(x.puntuacion)>=70).length; const incomplete=(data.personas||[]).filter(x=>!x.profesion||!x.email).length; app.innerHTML=`<div class="content"><div class="cards">${card('Personas',data.personas.length)}${card('Proyectos',data.proyectos.length)}${card('Necesidades abiertas',data.necesidades.filter(x=>String(x.estado).toLowerCase()!=='cubierta').length)}${card('Matches',data.matches.length)}${card('Matches ≥70%',high)}${card('Equipos',data.equipos.length)}${card('Perfiles incompletos',incomplete)}${card('Documentos',data.documentos.length)}</div><div class="split" style="margin-top:16px"><div class="card"><h3>Proyectos por etapa</h3>${stageList(data.proyectos)}</div><div class="card"><h3>Prioridad operativa</h3><p class="muted">Las necesidades se cruzan exclusivamente contra capacidades poseídas. Nunca se registran necesidades como capacidades personales.</p><button id="recompute">Recalcular matches</button></div></div></div>`; document.querySelector('#recompute').onclick=async()=>{try{const r=await api.recompute();alert(`${r.created} matches nuevos`);go('matches')}catch(e){alert(e.message)}}; }
function card(k,v){return `<div class="card"><div class="muted">${esc(k)}</div><div class="metric">${esc(v)}</div></div>`}
function stageList(items){ const m={}; for(const p of items)m[p.etapa||'Sin confirmar']=(m[p.etapa||'Sin confirmar']||0)+1; return Object.entries(m).map(([k,v])=>`<p><span class="badge">${esc(k)}</span> <strong>${v}</strong></p>`).join('')||'<p class="muted">Sin información todavía.</p>'; }

async function entityView(entity){ const rows=await api.list(entity); const cols=columns[entity]||Object.keys(rows[0]||{}).slice(0,8); app.innerHTML=`<div class="content"><div class="toolbar"><div><strong>${rows.length}</strong> registros</div><div>${entity==='documentos'?'<button id="upload">Subir documento</button>':''}${formFields[entity]?` <button id="new">Nuevo</button>`:''}</div></div>${table(rows,cols,entity)}</div>`; if(document.querySelector('#new'))document.querySelector('#new').onclick=()=>openForm(entity); if(document.querySelector('#upload'))document.querySelector('#upload').onclick=openUpload; document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openForm(entity,rows.find(r=>r.id===b.dataset.edit))); document.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(confirm(`Dar de baja lógica ${b.dataset.del}?`)){await api.remove(entity,b.dataset.del);go(entity)}}); }
function table(rows,cols,entity){ if(!rows.length)return '<div class="table-wrap"><div class="empty">Sin información todavía.</div></div>'; return `<div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${esc(c)}</th>`).join('')}<th>Acciones</th></tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${c==='url'&&r[c]?`<a href="${esc(r[c])}" target="_blank">Abrir</a>`:esc(r[c])}</td>`).join('')}<td><div class="actions">${formFields[entity]?`<button class="secondary" data-edit="${esc(r.id)}">Editar</button>`:''}<button class="danger" data-del="${esc(r.id)}">Baja</button></div></td></tr>`).join('')}</tbody></table></div>`; }

function openForm(entity,row={}){ const modal=document.querySelector('#modal'); document.querySelector('#modalTitle').textContent=`${row.id?'Editar':'Nuevo'} ${labels[entity]}`; document.querySelector('#modalBody').innerHTML=`<div class="grid">${formFields[entity].map(f=>field(f,row[f]??'')).join('')}</div>`; const form=document.querySelector('#modalForm'); form.onsubmit=async e=>{e.preventDefault(); if(e.submitter?.value==='cancel'){modal.close();return} const fd=new FormData(form); const data={}; for(const f of formFields[entity]) data[f]=fd.get(f)||''; try{ row.id?await api.update(entity,row.id,data):await api.create(entity,data); modal.close(); go(entity); }catch(err){alert(err.message)} }; modal.showModal(); }
function field(name,value){ const long=/descripcion|experiencia|evidencia|observaciones|preguntas|detalle|notas|proximos|necesidades|validaciones|integrantes|roles|capacidades_/i.test(name); return `<div class="field"><label>${esc(name)}</label>${long?`<textarea name="${esc(name)}">${esc(value)}</textarea>`:`<input name="${esc(name)}" value="${esc(value)}">`}</div>`; }
function openUpload(){ const modal=document.querySelector('#modal'); document.querySelector('#modalTitle').textContent='Subir documento a Google Drive'; document.querySelector('#modalBody').innerHTML='<div class="grid"><div class="field"><label>Archivo</label><input name="file" type="file" required></div><div class="field"><label>Persona ID</label><input name="persona_id"></div><div class="field"><label>Proyecto ID</label><input name="proyecto_id"></div><div class="field"><label>Origen</label><input name="origen" value="carga manual"></div></div>'; const form=document.querySelector('#modalForm'); form.onsubmit=async e=>{e.preventDefault();if(e.submitter?.value==='cancel'){modal.close();return}try{await api.uploadDocument(new FormData(form));modal.close();go('documentos')}catch(err){alert(err.message)}}; modal.showModal(); }

async function searchGlobal(){ const q=document.querySelector('#globalSearch').value.trim(); if(!q)return; title.textContent='Búsqueda'; subtitle.textContent=`Resultados para “${q}”`; app.innerHTML='<div class="content"><div class="empty">Buscando…</div></div>'; try{const d=await api.search(q); app.innerHTML=`<div class="content">${d.results.length?d.results.map(x=>`<div class="card" style="margin-bottom:10px"><span class="badge">${esc(x.entity)}</span><h3>${esc(x.label)}</h3><small>${esc(x.id)}</small></div>`).join(''):'<div class="empty">Sin resultados.</div>'}</div>`}catch(e){fail(e)} }
async function settings(){ let h; try{h=await api.health()}catch(e){h={ok:false,error:e.message}} app.innerHTML=`<div class="content"><div class="card"><h3>Estado</h3><pre>${esc(JSON.stringify(h,null,2))}</pre><div class="actions"><button id="bootstrap">Inicializar hojas</button><button class="secondary" id="setToken">Cambiar token de sesión</button></div><p class="muted">Los secretos Google y Cloudflare nunca se guardan en el navegador ni en GitHub. El token de administración solo vive en sessionStorage y desaparece al cerrar la sesión del navegador.</p></div></div>`; document.querySelector('#bootstrap').onclick=async()=>{try{const r=await api.bootstrap();alert(`Hojas verificadas: ${r.sheets.join(', ')}`)}catch(e){alert(e.message)}}; document.querySelector('#setToken').onclick=document.querySelector('#authBtn').onclick; }
const initial=(location.hash||'#dashboard').slice(1); go(views.includes(initial)?initial:'dashboard');
